### ISSUE TITLE
dscomputers.py --passwordhashes broken

### ISSUE THREAD

**Issue by brandoncasaba** [csababarta/ntdsxtract#10]
Trying to extract machine accounts and failing. Works fine with ImpDump (https://github.com/HarmJ0y/ImpDump) and CredDump. 

command: 
ntdsxtract/dscomputers.py output.export/datatable.4 work --syshive system --passwordhashes --pwdformat john --ntoutfile nt --lmoutfile lm

...
Password hashes:[!] Error! format_john() takes exactly 4 arguments (3 given)

Looks like you're missing the sid arg? Quest test editing the code to pass in an empty string for a sid does get some output however.

The ophc argument also doesn't seem to return anything, but no errors. 
edit: it seems there is a logic problem there, ntlm passwords are never written with ophc format flag...

**Comment by brandoncasaba** [comment]
Added a pull request with a fix for the john portion. See https://github.com/csababarta/ntdsxtract/pull/11

**Comment by csababarta** [comment]
Hi there,

I have fixed the issue. Thank you for reporting it.

**Comment by brandoncasaba** [comment]
Thank you, looks fixed
