### ISSUE TITLE
Issue with Windows 2012

### ISSUE THREAD

**Issue by po0lpy0x0c** [csababarta/ntdsxtract#7]
Hi, 
Thanks a lot for this really (REALLY) good tool.
I'v got a problem when using dsusers.py with a Windows 2012 ntds.dit, any help will be appreciated :)

-------------------------------------------------------------------------------------------------
$ python dsusers.py $dir/ntds.dit.export/datatable.4 $dir/ntds.dit.export/link_table.6 $dir/results --passwordhashes --passwordhistory --syshive $dir/SYSTEM --ntoutfile $dir/AD_NT_pass --pwdformat john --lmoutfile $dir/AD_LM_pass

[+] Started at: Wed, --
[+] Started with options:
	[-] Extracting password hashes
	[-] Extracting password history
	[-] NT hash output filename: /tmp/INTERNE/PASSWORD/AD_NT_pass
	[-] Hash output format: john
	[-] LM hash output filename: /tmp/PASSWORD/AD_LM_pass
[+] Initialising engine...
[+] Loading saved map files (Stage 1)...
[+] Loading saved map files (Stage 2)...

List of users:
==============Traceback (most recent call last):
  File "dsusers.py", line 468, in <module>
    for recordid in dsMapRecordIdByTypeId[utype]:
KeyError: 1481

**Comment by csababarta** [comment]
Hi,

it seems that the ntds.dit you are trying to process is corrupt. The OS caches the modifications in memory and the version that you extract from the disk is not always the latest. Therefore sometimes you won't be able to process it with the framework. In these cases the only way to get it processed is to extract it from the system again.
