### ISSUE TITLE
dsusers.py not extracting disabled account information.

### ISSUE THREAD

**Issue by powderspecial600** [csababarta/ntdsxtract#8]
It appears that in this version compared to the 1.0 version it is not extracting user information who's accounts are marked disabled.  Examples would be the guest account and others that are manually set to disabled.  If I run it in the 1.0 version I see them, but in the 1.3.1 version I do not.  Could this be added back in?

**Comment by brandoncasaba** [comment]
I couldn't for the life of me get KRBTGT to spit out which seems to be related to this bug...

It seems this is a regression with commit 247db90 which adds the following lines in dsusers.py ~437
```python
        if user.isActive == True:
            if user.isLocked == False and user.isDisabled == False:
                processUser(user)
        elif only_locked == True:
            if user.isLocked == True:
                processUser(user)
        else:
            processUser(user)
```

For a quick fix, just comment everything except the last processUser line so everything gets processed.

If I'm missing something with flags to pass in, let me know...

**Comment by csababarta** [comment]
Hi,

could you please try the version that I have just checked in? I believe I found the problem and fixed it. Please let me know if it works.

Thanks

**Comment by powderspecial600** [comment]
This appears to be fixed.  I now see a ACCOUNTDISABLE flag being set under the User Account Control.  This looks good, closing the issue.

**Comment by brandoncasaba** [comment]
Looks fixed :+1:
